vich_uploader:
    db_driver: orm
    mappings:
        club_image:
            uri_prefix: /images/clubs
            upload_destination: '%kernel.project_dir%/public/images/clubs'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_remove: true
            delete_on_update: false
            inject_on_load: true
        blog_image:
            uri_prefix: /images/blogs
            upload_destination: '%kernel.project_dir%/public/images/blogs'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
        user_image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
        user_file:
            uri_prefix: /documents/users
            upload_destination: '%kernel.project_dir%/public/documents/users'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true